// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: documents.sql

package store

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const listDocuments = `-- name: ListDocuments :many
SELECT d.id, d.title, d.current_version_id, d.declared_year, d.created_at,
 v.state, v.sha256, v.byte_size, v.requested_pages, v.indexed_pages, v.total_pages,
 v.parser_version, v.embedding_version, v.error_json, v.build_usage
FROM documents d JOIN document_versions v ON v.id=d.current_version_id
WHERE d.tenant_id=$1 AND d.revoked_at IS NULL ORDER BY d.created_at DESC
`

type ListDocumentsRow struct {
	ID               pgtype.UUID        `json:"id"`
	Title            string             `json:"title"`
	CurrentVersionID pgtype.UUID        `json:"current_version_id"`
	DeclaredYear     pgtype.Int4        `json:"declared_year"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	State            string             `json:"state"`
	Sha256           string             `json:"sha256"`
	ByteSize         int64              `json:"byte_size"`
	RequestedPages   []int32            `json:"requested_pages"`
	IndexedPages     []int32            `json:"indexed_pages"`
	TotalPages       pgtype.Int4        `json:"total_pages"`
	ParserVersion    pgtype.Text        `json:"parser_version"`
	EmbeddingVersion pgtype.Text        `json:"embedding_version"`
	ErrorJson        json.RawMessage    `json:"error_json"`
	BuildUsage       json.RawMessage    `json:"build_usage"`
}

func (q *Queries) ListDocuments(ctx context.Context, tenantID string) ([]ListDocumentsRow, error) {
	rows, err := q.db.Query(ctx, listDocuments, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDocumentsRow{}
	for rows.Next() {
		var i ListDocumentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.CurrentVersionID,
			&i.DeclaredYear,
			&i.CreatedAt,
			&i.State,
			&i.Sha256,
			&i.ByteSize,
			&i.RequestedPages,
			&i.IndexedPages,
			&i.TotalPages,
			&i.ParserVersion,
			&i.EmbeddingVersion,
			&i.ErrorJson,
			&i.BuildUsage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunEvents = `-- name: ListRunEvents :many
SELECT run_id, sequence, event_type, payload, occurred_at FROM run_events WHERE run_id=$1 AND sequence>$2 ORDER BY sequence LIMIT 1000
`

type ListRunEventsParams struct {
	RunID    pgtype.UUID `json:"run_id"`
	Sequence int64       `json:"sequence"`
}

func (q *Queries) ListRunEvents(ctx context.Context, arg ListRunEventsParams) ([]RunEvent, error) {
	rows, err := q.db.Query(ctx, listRunEvents, arg.RunID, arg.Sequence)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RunEvent{}
	for rows.Next() {
		var i RunEvent
		if err := rows.Scan(
			&i.RunID,
			&i.Sequence,
			&i.EventType,
			&i.Payload,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markParseFailed = `-- name: MarkParseFailed :exec
UPDATE document_versions SET state='FAILED', error_json=$2
WHERE id=$1 AND state IN ('QUEUED','PARSING')
`

type MarkParseFailedParams struct {
	ID        pgtype.UUID     `json:"id"`
	ErrorJson json.RawMessage `json:"error_json"`
}

func (q *Queries) MarkParseFailed(ctx context.Context, arg MarkParseFailedParams) error {
	_, err := q.db.Exec(ctx, markParseFailed, arg.ID, arg.ErrorJson)
	return err
}

const markParsing = `-- name: MarkParsing :execrows
UPDATE document_versions SET state='PARSING' WHERE id=$1 AND state='QUEUED'
`

func (q *Queries) MarkParsing(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markParsing, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const readDocumentVersion = `-- name: ReadDocumentVersion :one
SELECT v.id, v.document_id, v.sha256, v.blob_ref, v.byte_size, v.source_url, v.requested_pages, v.indexed_pages, v.total_pages, v.state, v.parser_version, v.embedding_version, v.error_json, v.build_usage, v.created_at, v.ready_at, d.title, d.tenant_id, d.current_version_id, d.declared_year
FROM document_versions v JOIN documents d ON d.id=v.document_id
WHERE v.id=$1 AND d.tenant_id=$2 AND d.revoked_at IS NULL
`

type ReadDocumentVersionParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID string      `json:"tenant_id"`
}

type ReadDocumentVersionRow struct {
	ID               pgtype.UUID        `json:"id"`
	DocumentID       pgtype.UUID        `json:"document_id"`
	Sha256           string             `json:"sha256"`
	BlobRef          string             `json:"blob_ref"`
	ByteSize         int64              `json:"byte_size"`
	SourceUrl        string             `json:"source_url"`
	RequestedPages   []int32            `json:"requested_pages"`
	IndexedPages     []int32            `json:"indexed_pages"`
	TotalPages       pgtype.Int4        `json:"total_pages"`
	State            string             `json:"state"`
	ParserVersion    pgtype.Text        `json:"parser_version"`
	EmbeddingVersion pgtype.Text        `json:"embedding_version"`
	ErrorJson        json.RawMessage    `json:"error_json"`
	BuildUsage       json.RawMessage    `json:"build_usage"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	ReadyAt          pgtype.Timestamptz `json:"ready_at"`
	Title            string             `json:"title"`
	TenantID         string             `json:"tenant_id"`
	CurrentVersionID pgtype.UUID        `json:"current_version_id"`
	DeclaredYear     pgtype.Int4        `json:"declared_year"`
}

func (q *Queries) ReadDocumentVersion(ctx context.Context, arg ReadDocumentVersionParams) (ReadDocumentVersionRow, error) {
	row := q.db.QueryRow(ctx, readDocumentVersion, arg.ID, arg.TenantID)
	var i ReadDocumentVersionRow
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.Sha256,
		&i.BlobRef,
		&i.ByteSize,
		&i.SourceUrl,
		&i.RequestedPages,
		&i.IndexedPages,
		&i.TotalPages,
		&i.State,
		&i.ParserVersion,
		&i.EmbeddingVersion,
		&i.ErrorJson,
		&i.BuildUsage,
		&i.CreatedAt,
		&i.ReadyAt,
		&i.Title,
		&i.TenantID,
		&i.CurrentVersionID,
		&i.DeclaredYear,
	)
	return i, err
}

const readRun = `-- name: ReadRun :one
SELECT id, tenant_id, idempotency_key, request_sha256, question, version_ids, provider, scope_token, trace_id, config_version, contract_json, state, answer_json, error_json, created_at, deadline_at, finished_at, cancel_requested_at FROM query_runs WHERE id=$1 AND tenant_id=$2
`

type ReadRunParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID string      `json:"tenant_id"`
}

func (q *Queries) ReadRun(ctx context.Context, arg ReadRunParams) (QueryRun, error) {
	row := q.db.QueryRow(ctx, readRun, arg.ID, arg.TenantID)
	var i QueryRun
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.IdempotencyKey,
		&i.RequestSha256,
		&i.Question,
		&i.VersionIds,
		&i.Provider,
		&i.ScopeToken,
		&i.TraceID,
		&i.ConfigVersion,
		&i.ContractJson,
		&i.State,
		&i.AnswerJson,
		&i.ErrorJson,
		&i.CreatedAt,
		&i.DeadlineAt,
		&i.FinishedAt,
		&i.CancelRequestedAt,
	)
	return i, err
}

const readRunCalls = `-- name: ReadRunCalls :many
SELECT attempt_id, provider, state, reserved_upper_cny::text, amount_cny::text,
 call_json, snapshot_json, created_at, finished_at
FROM llm_calls WHERE run_id=$1 ORDER BY created_at
`

type ReadRunCallsRow struct {
	AttemptID        pgtype.UUID        `json:"attempt_id"`
	Provider         string             `json:"provider"`
	State            string             `json:"state"`
	ReservedUpperCny string             `json:"reserved_upper_cny"`
	AmountCny        string             `json:"amount_cny"`
	CallJson         json.RawMessage    `json:"call_json"`
	SnapshotJson     json.RawMessage    `json:"snapshot_json"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	FinishedAt       pgtype.Timestamptz `json:"finished_at"`
}

func (q *Queries) ReadRunCalls(ctx context.Context, runID pgtype.UUID) ([]ReadRunCallsRow, error) {
	rows, err := q.db.Query(ctx, readRunCalls, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReadRunCallsRow{}
	for rows.Next() {
		var i ReadRunCallsRow
		if err := rows.Scan(
			&i.AttemptID,
			&i.Provider,
			&i.State,
			&i.ReservedUpperCny,
			&i.AmountCny,
			&i.CallJson,
			&i.SnapshotJson,
			&i.CreatedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeDocument = `-- name: RevokeDocument :execrows
UPDATE documents SET revoked_at=now() WHERE id=$1 AND tenant_id=$2 AND revoked_at IS NULL
`

type RevokeDocumentParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID string      `json:"tenant_id"`
}

func (q *Queries) RevokeDocument(ctx context.Context, arg RevokeDocumentParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeDocument, arg.ID, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
