// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

type Document struct {
	ID               pgtype.UUID        `json:"id"`
	TenantID         string             `json:"tenant_id"`
	Title            string             `json:"title"`
	CurrentVersionID pgtype.UUID        `json:"current_version_id"`
	DeclaredYear     pgtype.Int4        `json:"declared_year"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	RevokedAt        pgtype.Timestamptz `json:"revoked_at"`
}

type DocumentVersion struct {
	ID               pgtype.UUID        `json:"id"`
	DocumentID       pgtype.UUID        `json:"document_id"`
	Sha256           string             `json:"sha256"`
	BlobRef          string             `json:"blob_ref"`
	ByteSize         int64              `json:"byte_size"`
	SourceUrl        string             `json:"source_url"`
	RequestedPages   []int32            `json:"requested_pages"`
	IndexedPages     []int32            `json:"indexed_pages"`
	TotalPages       pgtype.Int4        `json:"total_pages"`
	State            string             `json:"state"`
	ParserVersion    pgtype.Text        `json:"parser_version"`
	EmbeddingVersion pgtype.Text        `json:"embedding_version"`
	ErrorJson        json.RawMessage    `json:"error_json"`
	BuildUsage       json.RawMessage    `json:"build_usage"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	ReadyAt          pgtype.Timestamptz `json:"ready_at"`
}

type EvidenceRegion struct {
	ID               pgtype.UUID     `json:"id"`
	VersionID        pgtype.UUID     `json:"version_id"`
	Page             int32           `json:"page"`
	Bbox             []float64       `json:"bbox"`
	PageWidth        float64         `json:"page_width"`
	PageHeight       float64         `json:"page_height"`
	Kind             string          `json:"kind"`
	OriginalText     string          `json:"original_text"`
	TextSha256       string          `json:"text_sha256"`
	ContextJson      json.RawMessage `json:"context_json"`
	ParserVersion    string          `json:"parser_version"`
	EmbeddingVersion string          `json:"embedding_version"`
	Embedding        pgvector.Vector `json:"embedding"`
	FtsTerms         string          `json:"fts_terms"`
	SearchVector     interface{}     `json:"search_vector"`
}

type ExperimentBudget struct {
	ID                string             `json:"id"`
	Currency          string             `json:"currency"`
	CapCny            pgtype.Numeric     `json:"cap_cny"`
	MaxRequests       int32              `json:"max_requests"`
	KnownEstimateCny  pgtype.Numeric     `json:"known_estimate_cny"`
	ReservedUpperCny  pgtype.Numeric     `json:"reserved_upper_cny"`
	AttemptedRequests int32              `json:"attempted_requests"`
	HaltedReason      pgtype.Text        `json:"halted_reason"`
	PriceVersion      string             `json:"price_version"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type LlmCall struct {
	AttemptID        pgtype.UUID        `json:"attempt_id"`
	RunID            pgtype.UUID        `json:"run_id"`
	Provider         string             `json:"provider"`
	State            string             `json:"state"`
	RequestJson      json.RawMessage    `json:"request_json"`
	ReservedUpperCny pgtype.Numeric     `json:"reserved_upper_cny"`
	AmountCny        pgtype.Numeric     `json:"amount_cny"`
	CallJson         json.RawMessage    `json:"call_json"`
	SnapshotJson     json.RawMessage    `json:"snapshot_json"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	FinishedAt       pgtype.Timestamptz `json:"finished_at"`
}

type QueryRun struct {
	ID                pgtype.UUID        `json:"id"`
	TenantID          string             `json:"tenant_id"`
	IdempotencyKey    string             `json:"idempotency_key"`
	RequestSha256     string             `json:"request_sha256"`
	Question          string             `json:"question"`
	VersionIds        []pgtype.UUID      `json:"version_ids"`
	Provider          string             `json:"provider"`
	ScopeToken        string             `json:"scope_token"`
	TraceID           pgtype.UUID        `json:"trace_id"`
	ConfigVersion     string             `json:"config_version"`
	ContractJson      json.RawMessage    `json:"contract_json"`
	State             string             `json:"state"`
	AnswerJson        json.RawMessage    `json:"answer_json"`
	ErrorJson         json.RawMessage    `json:"error_json"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	DeadlineAt        pgtype.Timestamptz `json:"deadline_at"`
	FinishedAt        pgtype.Timestamptz `json:"finished_at"`
	CancelRequestedAt pgtype.Timestamptz `json:"cancel_requested_at"`
}

type RunEvent struct {
	RunID      pgtype.UUID        `json:"run_id"`
	Sequence   int64              `json:"sequence"`
	EventType  string             `json:"event_type"`
	Payload    json.RawMessage    `json:"payload"`
	OccurredAt pgtype.Timestamptz `json:"occurred_at"`
}
