# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from crackrag.v1 import runtime_pb2 as crackrag_dot_v1_dot_runtime__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in crackrag/v1/runtime_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AIRuntimeStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Health = channel.unary_unary(
                '/crackrag.v1.AIRuntime/Health',
                request_serializer=crackrag_dot_v1_dot_runtime__pb2.Empty.SerializeToString,
                response_deserializer=crackrag_dot_v1_dot_runtime__pb2.HealthReply.FromString,
                _registered_method=True)
        self.Parse = channel.unary_unary(
                '/crackrag.v1.AIRuntime/Parse',
                request_serializer=crackrag_dot_v1_dot_runtime__pb2.ParseRequest.SerializeToString,
                response_deserializer=crackrag_dot_v1_dot_runtime__pb2.ParseReply.FromString,
                _registered_method=True)
        self.Embed = channel.unary_unary(
                '/crackrag.v1.AIRuntime/Embed',
                request_serializer=crackrag_dot_v1_dot_runtime__pb2.EmbedRequest.SerializeToString,
                response_deserializer=crackrag_dot_v1_dot_runtime__pb2.EmbedReply.FromString,
                _registered_method=True)
        self.RunQuery = channel.unary_stream(
                '/crackrag.v1.AIRuntime/RunQuery',
                request_serializer=crackrag_dot_v1_dot_runtime__pb2.QueryRequest.SerializeToString,
                response_deserializer=crackrag_dot_v1_dot_runtime__pb2.RuntimeEvent.FromString,
                _registered_method=True)
        self.CancelRun = channel.unary_unary(
                '/crackrag.v1.AIRuntime/CancelRun',
                request_serializer=crackrag_dot_v1_dot_runtime__pb2.M3Request.SerializeToString,
                response_deserializer=crackrag_dot_v1_dot_runtime__pb2.JsonReply.FromString,
                _registered_method=True)
        self.ResumeJob = channel.unary_unary(
                '/crackrag.v1.AIRuntime/ResumeJob',
                request_serializer=crackrag_dot_v1_dot_runtime__pb2.M3Request.SerializeToString,
                response_deserializer=crackrag_dot_v1_dot_runtime__pb2.JsonReply.FromString,
                _registered_method=True)


class AIRuntimeServicer:
    """Missing associated documentation comment in .proto file."""

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Parse(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Embed(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunQuery(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelRun(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResumeJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AIRuntimeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=crackrag_dot_v1_dot_runtime__pb2.Empty.FromString,
                    response_serializer=crackrag_dot_v1_dot_runtime__pb2.HealthReply.SerializeToString,
            ),
            'Parse': grpc.unary_unary_rpc_method_handler(
                    servicer.Parse,
                    request_deserializer=crackrag_dot_v1_dot_runtime__pb2.ParseRequest.FromString,
                    response_serializer=crackrag_dot_v1_dot_runtime__pb2.ParseReply.SerializeToString,
            ),
            'Embed': grpc.unary_unary_rpc_method_handler(
                    servicer.Embed,
                    request_deserializer=crackrag_dot_v1_dot_runtime__pb2.EmbedRequest.FromString,
                    response_serializer=crackrag_dot_v1_dot_runtime__pb2.EmbedReply.SerializeToString,
            ),
            'RunQuery': grpc.unary_stream_rpc_method_handler(
                    servicer.RunQuery,
                    request_deserializer=crackrag_dot_v1_dot_runtime__pb2.QueryRequest.FromString,
                    response_serializer=crackrag_dot_v1_dot_runtime__pb2.RuntimeEvent.SerializeToString,
            ),
            'CancelRun': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelRun,
                    request_deserializer=crackrag_dot_v1_dot_runtime__pb2.M3Request.FromString,
                    response_serializer=crackrag_dot_v1_dot_runtime__pb2.JsonReply.SerializeToString,
            ),
            'ResumeJob': grpc.unary_unary_rpc_method_handler(
                    servicer.ResumeJob,
                    request_deserializer=crackrag_dot_v1_dot_runtime__pb2.M3Request.FromString,
                    response_serializer=crackrag_dot_v1_dot_runtime__pb2.JsonReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'crackrag.v1.AIRuntime', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('crackrag.v1.AIRuntime', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AIRuntime:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crackrag.v1.AIRuntime/Health',
            crackrag_dot_v1_dot_runtime__pb2.Empty.SerializeToString,
            crackrag_dot_v1_dot_runtime__pb2.HealthReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Parse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crackrag.v1.AIRuntime/Parse',
            crackrag_dot_v1_dot_runtime__pb2.ParseRequest.SerializeToString,
            crackrag_dot_v1_dot_runtime__pb2.ParseReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Embed(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crackrag.v1.AIRuntime/Embed',
            crackrag_dot_v1_dot_runtime__pb2.EmbedRequest.SerializeToString,
            crackrag_dot_v1_dot_runtime__pb2.EmbedReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunQuery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/crackrag.v1.AIRuntime/RunQuery',
            crackrag_dot_v1_dot_runtime__pb2.QueryRequest.SerializeToString,
            crackrag_dot_v1_dot_runtime__pb2.RuntimeEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crackrag.v1.AIRuntime/CancelRun',
            crackrag_dot_v1_dot_runtime__pb2.M3Request.SerializeToString,
            crackrag_dot_v1_dot_runtime__pb2.JsonReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResumeJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crackrag.v1.AIRuntime/ResumeJob',
            crackrag_dot_v1_dot_runtime__pb2.M3Request.SerializeToString,
            crackrag_dot_v1_dot_runtime__pb2.JsonReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class DataToolsStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SearchDocuments = channel.unary_unary(
                '/crackrag.v1.DataTools/SearchDocuments',
                request_serializer=crackrag_dot_v1_dot_runtime__pb2.SearchRequest.SerializeToString,
                response_deserializer=crackrag_dot_v1_dot_runtime__pb2.SearchReply.FromString,
                _registered_method=True)
        self.OpenDocument = channel.unary_unary(
                '/crackrag.v1.DataTools/OpenDocument',
                request_serializer=crackrag_dot_v1_dot_runtime__pb2.OpenRequest.SerializeToString,
                response_deserializer=crackrag_dot_v1_dot_runtime__pb2.OpenReply.FromString,
                _registered_method=True)
        self.ReserveCall = channel.unary_unary(
                '/crackrag.v1.DataTools/ReserveCall',
                request_serializer=crackrag_dot_v1_dot_runtime__pb2.ReserveRequest.SerializeToString,
                response_deserializer=crackrag_dot_v1_dot_runtime__pb2.ReserveReply.FromString,
                _registered_method=True)
        self.SettleCall = channel.unary_unary(
                '/crackrag.v1.DataTools/SettleCall',
                request_serializer=crackrag_dot_v1_dot_runtime__pb2.SettleRequest.SerializeToString,
                response_deserializer=crackrag_dot_v1_dot_runtime__pb2.Empty.FromString,
                _registered_method=True)
        self.ResolveConcepts = channel.unary_unary(
                '/crackrag.v1.DataTools/ResolveConcepts',
                request_serializer=crackrag_dot_v1_dot_runtime__pb2.ResolveRequest.SerializeToString,
                response_deserializer=crackrag_dot_v1_dot_runtime__pb2.JsonReply.FromString,
                _registered_method=True)
        self.GetCoverage = channel.unary_unary(
                '/crackrag.v1.DataTools/GetCoverage',
                request_serializer=crackrag_dot_v1_dot_runtime__pb2.FactsRequest.SerializeToString,
                response_deserializer=crackrag_dot_v1_dot_runtime__pb2.JsonReply.FromString,
                _registered_method=True)
        self.ReadFacts = channel.unary_unary(
                '/crackrag.v1.DataTools/ReadFacts',
                request_serializer=crackrag_dot_v1_dot_runtime__pb2.FactsRequest.SerializeToString,
                response_deserializer=crackrag_dot_v1_dot_runtime__pb2.JsonReply.FromString,
                _registered_method=True)


class DataToolsServicer:
    """Missing associated documentation comment in .proto file."""

    def SearchDocuments(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OpenDocument(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReserveCall(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SettleCall(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResolveConcepts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCoverage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadFacts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DataToolsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SearchDocuments': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchDocuments,
                    request_deserializer=crackrag_dot_v1_dot_runtime__pb2.SearchRequest.FromString,
                    response_serializer=crackrag_dot_v1_dot_runtime__pb2.SearchReply.SerializeToString,
            ),
            'OpenDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.OpenDocument,
                    request_deserializer=crackrag_dot_v1_dot_runtime__pb2.OpenRequest.FromString,
                    response_serializer=crackrag_dot_v1_dot_runtime__pb2.OpenReply.SerializeToString,
            ),
            'ReserveCall': grpc.unary_unary_rpc_method_handler(
                    servicer.ReserveCall,
                    request_deserializer=crackrag_dot_v1_dot_runtime__pb2.ReserveRequest.FromString,
                    response_serializer=crackrag_dot_v1_dot_runtime__pb2.ReserveReply.SerializeToString,
            ),
            'SettleCall': grpc.unary_unary_rpc_method_handler(
                    servicer.SettleCall,
                    request_deserializer=crackrag_dot_v1_dot_runtime__pb2.SettleRequest.FromString,
                    response_serializer=crackrag_dot_v1_dot_runtime__pb2.Empty.SerializeToString,
            ),
            'ResolveConcepts': grpc.unary_unary_rpc_method_handler(
                    servicer.ResolveConcepts,
                    request_deserializer=crackrag_dot_v1_dot_runtime__pb2.ResolveRequest.FromString,
                    response_serializer=crackrag_dot_v1_dot_runtime__pb2.JsonReply.SerializeToString,
            ),
            'GetCoverage': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCoverage,
                    request_deserializer=crackrag_dot_v1_dot_runtime__pb2.FactsRequest.FromString,
                    response_serializer=crackrag_dot_v1_dot_runtime__pb2.JsonReply.SerializeToString,
            ),
            'ReadFacts': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadFacts,
                    request_deserializer=crackrag_dot_v1_dot_runtime__pb2.FactsRequest.FromString,
                    response_serializer=crackrag_dot_v1_dot_runtime__pb2.JsonReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'crackrag.v1.DataTools', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('crackrag.v1.DataTools', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DataTools:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SearchDocuments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crackrag.v1.DataTools/SearchDocuments',
            crackrag_dot_v1_dot_runtime__pb2.SearchRequest.SerializeToString,
            crackrag_dot_v1_dot_runtime__pb2.SearchReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OpenDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crackrag.v1.DataTools/OpenDocument',
            crackrag_dot_v1_dot_runtime__pb2.OpenRequest.SerializeToString,
            crackrag_dot_v1_dot_runtime__pb2.OpenReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReserveCall(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crackrag.v1.DataTools/ReserveCall',
            crackrag_dot_v1_dot_runtime__pb2.ReserveRequest.SerializeToString,
            crackrag_dot_v1_dot_runtime__pb2.ReserveReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SettleCall(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crackrag.v1.DataTools/SettleCall',
            crackrag_dot_v1_dot_runtime__pb2.SettleRequest.SerializeToString,
            crackrag_dot_v1_dot_runtime__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResolveConcepts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crackrag.v1.DataTools/ResolveConcepts',
            crackrag_dot_v1_dot_runtime__pb2.ResolveRequest.SerializeToString,
            crackrag_dot_v1_dot_runtime__pb2.JsonReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCoverage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crackrag.v1.DataTools/GetCoverage',
            crackrag_dot_v1_dot_runtime__pb2.FactsRequest.SerializeToString,
            crackrag_dot_v1_dot_runtime__pb2.JsonReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadFacts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crackrag.v1.DataTools/ReadFacts',
            crackrag_dot_v1_dot_runtime__pb2.FactsRequest.SerializeToString,
            crackrag_dot_v1_dot_runtime__pb2.JsonReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ExtractionControlStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.BeginExtraction = channel.unary_unary(
                '/crackrag.v1.ExtractionControl/BeginExtraction',
                request_serializer=crackrag_dot_v1_dot_runtime__pb2.BeginExtractionRequest.SerializeToString,
                response_deserializer=crackrag_dot_v1_dot_runtime__pb2.JsonReply.FromString,
                _registered_method=True)
        self.StoreCandidates = channel.unary_unary(
                '/crackrag.v1.ExtractionControl/StoreCandidates',
                request_serializer=crackrag_dot_v1_dot_runtime__pb2.CandidateRequest.SerializeToString,
                response_deserializer=crackrag_dot_v1_dot_runtime__pb2.JsonReply.FromString,
                _registered_method=True)
        self.ValidateCandidates = channel.unary_unary(
                '/crackrag.v1.ExtractionControl/ValidateCandidates',
                request_serializer=crackrag_dot_v1_dot_runtime__pb2.BatchRequest.SerializeToString,
                response_deserializer=crackrag_dot_v1_dot_runtime__pb2.JsonReply.FromString,
                _registered_method=True)
        self.BeginProbe = channel.unary_unary(
                '/crackrag.v1.ExtractionControl/BeginProbe',
                request_serializer=crackrag_dot_v1_dot_runtime__pb2.BatchRequest.SerializeToString,
                response_deserializer=crackrag_dot_v1_dot_runtime__pb2.JsonReply.FromString,
                _registered_method=True)
        self.CommitExtraction = channel.unary_unary(
                '/crackrag.v1.ExtractionControl/CommitExtraction',
                request_serializer=crackrag_dot_v1_dot_runtime__pb2.CommitRequest.SerializeToString,
                response_deserializer=crackrag_dot_v1_dot_runtime__pb2.JsonReply.FromString,
                _registered_method=True)
        self.DeriveFacts = channel.unary_unary(
                '/crackrag.v1.ExtractionControl/DeriveFacts',
                request_serializer=crackrag_dot_v1_dot_runtime__pb2.DeriveRequest.SerializeToString,
                response_deserializer=crackrag_dot_v1_dot_runtime__pb2.JsonReply.FromString,
                _registered_method=True)


class ExtractionControlServicer:
    """Missing associated documentation comment in .proto file."""

    def BeginExtraction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StoreCandidates(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateCandidates(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BeginProbe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CommitExtraction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeriveFacts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ExtractionControlServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'BeginExtraction': grpc.unary_unary_rpc_method_handler(
                    servicer.BeginExtraction,
                    request_deserializer=crackrag_dot_v1_dot_runtime__pb2.BeginExtractionRequest.FromString,
                    response_serializer=crackrag_dot_v1_dot_runtime__pb2.JsonReply.SerializeToString,
            ),
            'StoreCandidates': grpc.unary_unary_rpc_method_handler(
                    servicer.StoreCandidates,
                    request_deserializer=crackrag_dot_v1_dot_runtime__pb2.CandidateRequest.FromString,
                    response_serializer=crackrag_dot_v1_dot_runtime__pb2.JsonReply.SerializeToString,
            ),
            'ValidateCandidates': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateCandidates,
                    request_deserializer=crackrag_dot_v1_dot_runtime__pb2.BatchRequest.FromString,
                    response_serializer=crackrag_dot_v1_dot_runtime__pb2.JsonReply.SerializeToString,
            ),
            'BeginProbe': grpc.unary_unary_rpc_method_handler(
                    servicer.BeginProbe,
                    request_deserializer=crackrag_dot_v1_dot_runtime__pb2.BatchRequest.FromString,
                    response_serializer=crackrag_dot_v1_dot_runtime__pb2.JsonReply.SerializeToString,
            ),
            'CommitExtraction': grpc.unary_unary_rpc_method_handler(
                    servicer.CommitExtraction,
                    request_deserializer=crackrag_dot_v1_dot_runtime__pb2.CommitRequest.FromString,
                    response_serializer=crackrag_dot_v1_dot_runtime__pb2.JsonReply.SerializeToString,
            ),
            'DeriveFacts': grpc.unary_unary_rpc_method_handler(
                    servicer.DeriveFacts,
                    request_deserializer=crackrag_dot_v1_dot_runtime__pb2.DeriveRequest.FromString,
                    response_serializer=crackrag_dot_v1_dot_runtime__pb2.JsonReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'crackrag.v1.ExtractionControl', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('crackrag.v1.ExtractionControl', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ExtractionControl:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def BeginExtraction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crackrag.v1.ExtractionControl/BeginExtraction',
            crackrag_dot_v1_dot_runtime__pb2.BeginExtractionRequest.SerializeToString,
            crackrag_dot_v1_dot_runtime__pb2.JsonReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StoreCandidates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crackrag.v1.ExtractionControl/StoreCandidates',
            crackrag_dot_v1_dot_runtime__pb2.CandidateRequest.SerializeToString,
            crackrag_dot_v1_dot_runtime__pb2.JsonReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateCandidates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crackrag.v1.ExtractionControl/ValidateCandidates',
            crackrag_dot_v1_dot_runtime__pb2.BatchRequest.SerializeToString,
            crackrag_dot_v1_dot_runtime__pb2.JsonReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BeginProbe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crackrag.v1.ExtractionControl/BeginProbe',
            crackrag_dot_v1_dot_runtime__pb2.BatchRequest.SerializeToString,
            crackrag_dot_v1_dot_runtime__pb2.JsonReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CommitExtraction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crackrag.v1.ExtractionControl/CommitExtraction',
            crackrag_dot_v1_dot_runtime__pb2.CommitRequest.SerializeToString,
            crackrag_dot_v1_dot_runtime__pb2.JsonReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeriveFacts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crackrag.v1.ExtractionControl/DeriveFacts',
            crackrag_dot_v1_dot_runtime__pb2.DeriveRequest.SerializeToString,
            crackrag_dot_v1_dot_runtime__pb2.JsonReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ProbeToolsStub:
    """A probe capability never grants publication, SQL, code execution or mutation.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.OpenDocument = channel.unary_unary(
                '/crackrag.v1.ProbeTools/OpenDocument',
                request_serializer=crackrag_dot_v1_dot_runtime__pb2.ProbeOpenRequest.SerializeToString,
                response_deserializer=crackrag_dot_v1_dot_runtime__pb2.OpenReply.FromString,
                _registered_method=True)


class ProbeToolsServicer:
    """A probe capability never grants publication, SQL, code execution or mutation.
    """

    def OpenDocument(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProbeToolsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'OpenDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.OpenDocument,
                    request_deserializer=crackrag_dot_v1_dot_runtime__pb2.ProbeOpenRequest.FromString,
                    response_serializer=crackrag_dot_v1_dot_runtime__pb2.OpenReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'crackrag.v1.ProbeTools', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('crackrag.v1.ProbeTools', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ProbeTools:
    """A probe capability never grants publication, SQL, code execution or mutation.
    """

    @staticmethod
    def OpenDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crackrag.v1.ProbeTools/OpenDocument',
            crackrag_dot_v1_dot_runtime__pb2.ProbeOpenRequest.SerializeToString,
            crackrag_dot_v1_dot_runtime__pb2.OpenReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class JobControlStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateJob = channel.unary_unary(
                '/crackrag.v1.JobControl/CreateJob',
                request_serializer=crackrag_dot_v1_dot_runtime__pb2.M3Request.SerializeToString,
                response_deserializer=crackrag_dot_v1_dot_runtime__pb2.JsonReply.FromString,
                _registered_method=True)
        self.ClaimJob = channel.unary_unary(
                '/crackrag.v1.JobControl/ClaimJob',
                request_serializer=crackrag_dot_v1_dot_runtime__pb2.M3Request.SerializeToString,
                response_deserializer=crackrag_dot_v1_dot_runtime__pb2.JsonReply.FromString,
                _registered_method=True)
        self.RenewJob = channel.unary_unary(
                '/crackrag.v1.JobControl/RenewJob',
                request_serializer=crackrag_dot_v1_dot_runtime__pb2.M3Request.SerializeToString,
                response_deserializer=crackrag_dot_v1_dot_runtime__pb2.JsonReply.FromString,
                _registered_method=True)
        self.ObservePrefix = channel.unary_unary(
                '/crackrag.v1.JobControl/ObservePrefix',
                request_serializer=crackrag_dot_v1_dot_runtime__pb2.M3Request.SerializeToString,
                response_deserializer=crackrag_dot_v1_dot_runtime__pb2.JsonReply.FromString,
                _registered_method=True)
        self.FinishJob = channel.unary_unary(
                '/crackrag.v1.JobControl/FinishJob',
                request_serializer=crackrag_dot_v1_dot_runtime__pb2.M3Request.SerializeToString,
                response_deserializer=crackrag_dot_v1_dot_runtime__pb2.JsonReply.FromString,
                _registered_method=True)
        self.CancelJobs = channel.unary_unary(
                '/crackrag.v1.JobControl/CancelJobs',
                request_serializer=crackrag_dot_v1_dot_runtime__pb2.M3Request.SerializeToString,
                response_deserializer=crackrag_dot_v1_dot_runtime__pb2.JsonReply.FromString,
                _registered_method=True)
        self.GetJob = channel.unary_unary(
                '/crackrag.v1.JobControl/GetJob',
                request_serializer=crackrag_dot_v1_dot_runtime__pb2.M3Request.SerializeToString,
                response_deserializer=crackrag_dot_v1_dot_runtime__pb2.JsonReply.FromString,
                _registered_method=True)


class JobControlServicer:
    """Missing associated documentation comment in .proto file."""

    def CreateJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClaimJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RenewJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ObservePrefix(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FinishJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelJobs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_JobControlServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateJob': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateJob,
                    request_deserializer=crackrag_dot_v1_dot_runtime__pb2.M3Request.FromString,
                    response_serializer=crackrag_dot_v1_dot_runtime__pb2.JsonReply.SerializeToString,
            ),
            'ClaimJob': grpc.unary_unary_rpc_method_handler(
                    servicer.ClaimJob,
                    request_deserializer=crackrag_dot_v1_dot_runtime__pb2.M3Request.FromString,
                    response_serializer=crackrag_dot_v1_dot_runtime__pb2.JsonReply.SerializeToString,
            ),
            'RenewJob': grpc.unary_unary_rpc_method_handler(
                    servicer.RenewJob,
                    request_deserializer=crackrag_dot_v1_dot_runtime__pb2.M3Request.FromString,
                    response_serializer=crackrag_dot_v1_dot_runtime__pb2.JsonReply.SerializeToString,
            ),
            'ObservePrefix': grpc.unary_unary_rpc_method_handler(
                    servicer.ObservePrefix,
                    request_deserializer=crackrag_dot_v1_dot_runtime__pb2.M3Request.FromString,
                    response_serializer=crackrag_dot_v1_dot_runtime__pb2.JsonReply.SerializeToString,
            ),
            'FinishJob': grpc.unary_unary_rpc_method_handler(
                    servicer.FinishJob,
                    request_deserializer=crackrag_dot_v1_dot_runtime__pb2.M3Request.FromString,
                    response_serializer=crackrag_dot_v1_dot_runtime__pb2.JsonReply.SerializeToString,
            ),
            'CancelJobs': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelJobs,
                    request_deserializer=crackrag_dot_v1_dot_runtime__pb2.M3Request.FromString,
                    response_serializer=crackrag_dot_v1_dot_runtime__pb2.JsonReply.SerializeToString,
            ),
            'GetJob': grpc.unary_unary_rpc_method_handler(
                    servicer.GetJob,
                    request_deserializer=crackrag_dot_v1_dot_runtime__pb2.M3Request.FromString,
                    response_serializer=crackrag_dot_v1_dot_runtime__pb2.JsonReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'crackrag.v1.JobControl', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('crackrag.v1.JobControl', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class JobControl:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crackrag.v1.JobControl/CreateJob',
            crackrag_dot_v1_dot_runtime__pb2.M3Request.SerializeToString,
            crackrag_dot_v1_dot_runtime__pb2.JsonReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClaimJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crackrag.v1.JobControl/ClaimJob',
            crackrag_dot_v1_dot_runtime__pb2.M3Request.SerializeToString,
            crackrag_dot_v1_dot_runtime__pb2.JsonReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RenewJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crackrag.v1.JobControl/RenewJob',
            crackrag_dot_v1_dot_runtime__pb2.M3Request.SerializeToString,
            crackrag_dot_v1_dot_runtime__pb2.JsonReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ObservePrefix(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crackrag.v1.JobControl/ObservePrefix',
            crackrag_dot_v1_dot_runtime__pb2.M3Request.SerializeToString,
            crackrag_dot_v1_dot_runtime__pb2.JsonReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FinishJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crackrag.v1.JobControl/FinishJob',
            crackrag_dot_v1_dot_runtime__pb2.M3Request.SerializeToString,
            crackrag_dot_v1_dot_runtime__pb2.JsonReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelJobs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crackrag.v1.JobControl/CancelJobs',
            crackrag_dot_v1_dot_runtime__pb2.M3Request.SerializeToString,
            crackrag_dot_v1_dot_runtime__pb2.JsonReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crackrag.v1.JobControl/GetJob',
            crackrag_dot_v1_dot_runtime__pb2.M3Request.SerializeToString,
            crackrag_dot_v1_dot_runtime__pb2.JsonReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
