import React,{useState} from 'react';
import {names,reasonText,shortTime,supportNames} from './workspace-model';
import type {Doc,HistoryItem} from './workspace-model';
import {pageSelectionError} from './pdf-page-suggestions';

export function DocumentLibrary({docs,selected,onSelect,readOnly,onUpload,onRevoke,fileRef,scopePages,onScopePages,year,onYear,uploading,pdfPages,fileChecking,fileError,scanNotice,suggestedPages,scanProgress,scanning,previewURL,onFileChange}:{docs:Doc[];selected:string[];onSelect:(next:string[])=>void;readOnly:boolean;onUpload:(event:React.FormEvent)=>void;onRevoke:(id:string)=>void;fileRef:React.RefObject<HTMLInputElement|null>;scopePages:string;onScopePages:(value:string)=>void;year:string;onYear:(value:string)=>void;uploading:boolean;pdfPages:number|null;fileChecking:boolean;fileError:string;scanNotice:string;suggestedPages:number[];scanProgress:number;scanning:boolean;previewURL:string;onFileChange:(file:File|null)=>void}){
 const needsScope=pdfPages!==null&&pdfPages>32;
 const pageProblem=pageSelectionError(scopePages,pdfPages);
 return <section className="card document-card"><div className="section-line"><h2>选择文档 <span className="count">{docs.length}</span></h2></div>
 {!readOnly&&<form onSubmit={onUpload} className="upload"><label className="file-label">导入 PDF<input ref={fileRef} type="file" accept="application/pdf,.pdf" aria-label="选择 PDF" required onChange={event=>onFileChange(event.target.files?.[0]||null)}/></label>
  {fileChecking&&<p className="hint">正在检查页数…</p>}
  {pdfPages!==null&&<p className="hint">这份文件共 {pdfPages} 页。{needsScope?'当前最多可处理 32 页，请选包含财务表的页面。':'可以直接上传，无需填写页码。'}</p>}
  {needsScope&&<><p className="hint">{scanning?`正在本机查找可能包含财务表的页面（${scanProgress}%）…`:'自动建议只供定位，仍需核对表头、单位与附注。'} {previewURL&&<a href={previewURL} target="_blank" rel="noreferrer">打开本地 PDF 核对</a>}</p>{suggestedPages.length>0&&<div className="page-suggestion"><span>建议页码：{suggestedPages.join('、')}</span><button className="secondary" type="button" onClick={()=>onScopePages(suggestedPages.join(','))}>使用建议</button></div>}</>}
  {fileError&&<p role="alert" className="inline-error">{fileError}</p>}
  {scanNotice&&<p className="hint">{scanNotice}</p>}
  <details className="upload-options" open={needsScope?true:undefined}><summary>{needsScope?'选择要分析的页码':'只分析指定页（可选）'}</summary><div className="two"><label className="label">页码范围<input value={scopePages} onChange={event=>onScopePages(event.target.value)} placeholder="例如 86,87" aria-label="页码范围"/></label><label className="label">报告年份<input value={year} onChange={event=>onYear(event.target.value)} placeholder="可选" aria-label="报告年份"/></label></div><p className="hint">页码以原 PDF 为准，最多 32 页；扫描页暂不支持。长年报可先在本地 PDF 中搜索“合并利润表”定位表格与附注页。</p></details>
  {scopePages&&pageProblem&&<p role="alert" className="inline-error">{pageProblem}</p>}
  <button className="secondary full" disabled={uploading||fileChecking||!!fileError||!!pageProblem}>{uploading?'正在上传…':'上传文档'}</button></form>}
 <div className="document-list">{docs.length===0?<div className="empty small">还没有可访问的文档。<br/>上传一份 PDF 开始。</div>:docs.map(doc=><article className="document" key={doc.id} data-document-id={doc.id}><label><input type="checkbox" checked={selected.includes(doc.id)} disabled={readOnly||doc.state!=='READY'} onChange={event=>onSelect(event.target.checked?[...selected,doc.id]:selected.filter(id=>id!==doc.id))}/><strong>{doc.title}</strong></label><div className="document-meta"><span className={`status ${doc.state.toLowerCase()}`}>{names[doc.state]||'处理中'}</span>{!readOnly&&<button className="text-button" type="button" onClick={()=>onRevoke(doc.id)} aria-label={`撤销访问 ${doc.title}`}>撤销访问</button>}</div>{doc.indexed_pages?.length>0&&<p className="hint">已索引：第 {doc.indexed_pages.join('、')} 页</p>}{doc.error_json&&<p className="inline-error">{reasonText(doc.error_json.reason_code)}</p>}</article>)}</div>{!readOnly&&<p className="hint">撤销访问后不再用于查询；原文件与审计记录仍保留。</p>}</section>;
}

export function HistoryPanel({history,cursor,busy,currentID,onRefresh,onSearch,onOpen,onRename,aliases,search}:{history:HistoryItem[];cursor:string;busy:boolean;currentID:string;onRefresh:(append?:boolean)=>void;onSearch:(term:string)=>void;onOpen:(id:string)=>void;onRename:(id:string,title:string)=>void;aliases:Record<string,string>;search:string}){
 const [draft,setDraft]=useState(search),[editing,setEditing]=useState(''),[title,setTitle]=useState('');
 return <section className="card history-card" id="recent-queries"><div className="section-line"><h2>最近查询</h2><button className="text-button" type="button" onClick={()=>onRefresh()} disabled={busy}>刷新</button></div>
  <form className="history-search" onSubmit={event=>{event.preventDefault();onSearch(draft)}}><input aria-label="搜索查询记录" value={draft} maxLength={120} onChange={event=>setDraft(event.target.value)} placeholder="搜索问题"/><button className="secondary" type="submit" disabled={busy}>搜索</button>{search&&<button className="text-button" type="button" onClick={()=>{setDraft('');onSearch('')}}>清除</button>}</form>
  {!history.length?<p className="hint">{search?'没有匹配的查询。可换个关键词。':'完成一次查询后，可从这里找回答案。'}</p>:history.map(item=><div className="history-entry" key={item.id}>{editing===item.id?<form className="history-rename" onSubmit={event=>{event.preventDefault();onRename(item.id,title.trim());setEditing('')}}><input aria-label="查询显示名称" value={title} maxLength={80} onChange={event=>setTitle(event.target.value)}/><button type="submit" disabled={!title.trim()}>保存</button><button className="secondary" type="button" onClick={()=>setEditing('')}>取消</button></form>:<><button className={`history-item ${currentID===item.id?'selected':''}`} onClick={()=>onOpen(item.id)} type="button"><strong>{aliases[item.id]||item.question}</strong>{aliases[item.id]&&<small>{item.question}</small>}<span>{shortTime(item.created_at)} · {supportNames[item.answer_status]||names[item.state]||'处理中'} · {item.model_calls} 次{item.provider==='mock'?'模拟':'模型'}调用</span></button><button className="text-button rename-button" type="button" aria-label={`重命名 ${aliases[item.id]||item.question}`} onClick={()=>{setEditing(item.id);setTitle(aliases[item.id]||item.question)}}>改名</button></>}</div>)}
  {cursor&&<button className="secondary full" type="button" disabled={busy} onClick={()=>onRefresh(true)}>查看更多</button>}<p className="hint">显示名称只保存在当前登录会话，不改动原问题或审计记录。</p></section>;
}
