import React from 'react';
import {assetUrl} from './urls';
import {demoStepNames,expandFollowup} from './workspace-model';
import type {DemoStep} from './workspace-model';

export function DemoGuide({readOnly,demoSteps,demoPosition,busy,onStep,onSuggest}:{readOnly:boolean;demoSteps?:DemoStep[];demoPosition:number;busy:boolean;onStep:(step:DemoStep)=>void;onSuggest:(text:string,build?:boolean,sample?:string)=>void}){
 return <section className="card demo-guide" aria-label="演示指南"><p className="eyebrow">{readOnly?'已记录的真实问答':'从提问到复用'}</p><h2>{readOnly?'点开一次真实年报问答':'从原页核对，到下次直接复用'}</h2>
 {readOnly&&demoSteps?<><p>按顺序选择一步，再点击“查看录制结果”。前四步来自同一轮真实运行；最后一步是单独的模拟缺证据示例。</p><div className="suggestions">{demoSteps.map((step,index)=><button type="button" className="secondary" key={`${step.role}-${index}`} disabled={busy||index!==demoPosition} onClick={()=>onStep(step)}>{demoStepNames[step.role]||`第 ${index+1} 步`}</button>)}</div><p className="hint">这里不连接模型；点击只回放当时的结果。原始真实运行视频和费用记录可从页面上方查看。</p></>:<><ol><li>导入<a href={assetUrl('samples/financial.pdf')} download>自制财务样例</a>，等待文档就绪。</li><li>首次提问后，打开原页核对数字与口径。</li><li>明确选择保存已核对数字，再问同一问题，看本次是否无需模型调用。</li><li>导入<a href={assetUrl('samples/ambiguous.pdf')} download>缺附注样例</a>，看系统如何说明证据不足。</li></ol><div className="suggestions"><button className="secondary" disabled={busy} onClick={()=>onSuggest('样例控股2024年营业收入是多少？')}>① 看第一次回答</button><button className="secondary" disabled={busy} onClick={()=>onSuggest('样例控股2024年营业收入是多少？',true)}>② 保存可复用数字</button><button className="secondary" disabled={busy} onClick={()=>onSuggest('样例控股2024年营业收入是多少？')}>③ 再问同一问题</button><button className="secondary" disabled={busy} onClick={()=>onSuggest('样例控股2024年净利润是多少？',false,'ambiguous.pdf')}>④ 看证据不足</button></div><p className="hint">保存数字可能产生额外模型费用；样例数字是自制材料，不是真实公司披露。</p></>}
 </section>;
}

export function QueryComposer({readOnly,selectedCount,question,onQuestion,buildFacts,onBuildFacts,executionPolicy,onPolicy,busy,submitting,allReady,onSubmit,onCancel,canCancel}:{readOnly:boolean;selectedCount:number;question:string;onQuestion:(value:string)=>void;buildFacts:boolean;onBuildFacts:(value:boolean)=>void;executionPolicy:string;onPolicy:(value:string)=>void;busy:boolean;submitting:boolean;allReady:boolean;onSubmit:(event:React.FormEvent)=>void;onCancel:()=>void;canCancel:boolean}){
 return <section className="card query-card" id="question-composer"><div className="section-line"><h2>{readOnly?'这一步问了什么':'向原文提问'}</h2><span className="hint">已选择 {selectedCount} 份文档</span></div><form onSubmit={onSubmit}><textarea aria-label="问题" placeholder={readOnly?'先从上方选择演示步骤':'例如：样例控股2024年营业收入是多少？'} value={question} readOnly={readOnly} onChange={event=>onQuestion(event.target.value)} maxLength={1000} rows={4}/>
 {!readOnly&&buildFacts&&<div className="save-policy"><label className="label">何时保存供后续复用<select aria-label="何时保存供后续复用" value={executionPolicy} disabled={busy} onChange={event=>onPolicy(event.target.value)}><option value="HOT_ONLY">条件合适时保存（默认）</option><option value="COLD_ALLOWED">立即保存，可能增加费用</option></select></label><p className="hint">这项选择只影响后续数字保存，不影响当前回答的核验。</p></div>}
 <div className="query-actions">{!readOnly&&<label className="build-facts"><input type="checkbox" checked={buildFacts} onChange={event=>onBuildFacts(event.target.checked)} disabled={busy} aria-label="为以后提问保存数字"/> 为以后提问保存数字</label>}<span className="hint">{readOnly?'这不会产生新的模型请求或费用。':'证据不足会明确说明。'}</span>{!readOnly&&canCancel&&<button type="button" className="secondary" onClick={onCancel} disabled={!canCancel}>{busy?'取消':'取消后续处理'}</button>}<button type="submit" disabled={busy||!allReady||!question.trim()}>{submitting?'正在提交…':readOnly?'查看录制结果':'查阅并回答'}</button></div></form></section>;
}

export function FollowupPanel({previous,draft,onDraft,onSubmit,onClose}:{previous:string;draft:string;onDraft:(value:string)=>void;onSubmit:(event:React.FormEvent)=>void;onClose:()=>void}){
 const expanded=expandFollowup(previous,draft);
 return <section className="card followup-card" aria-label="接着提问"><div className="section-line"><h2>接着这一问</h2><button type="button" className="text-button" onClick={onClose}>关闭</button></div><p className="hint">沿用上一问的文档；系统只会补全明确的年份或指标，不会猜测其他上下文。</p><form onSubmit={onSubmit}><label className="label">你的追问<input aria-label="追问内容" value={draft} onChange={event=>onDraft(event.target.value)} placeholder="例如：那 2023 年呢？"/></label>{draft&&<p className="followup-preview">{expanded?<><strong>将填入：</strong>{expanded}</>:'暂时无法安全补全；请写完整的公司、年份和指标。'}</p>}<button type="submit" disabled={!expanded}>填入提问框，确认后发送</button></form></section>;
}
